// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKSH0whlIJn012DRK3JwPE7b02kIUbV9o',
    appId: '1:212179119317:web:83d81da403d8ec13edc65c',
    messagingSenderId: '212179119317',
    projectId: 'login-72329',
    authDomain: 'login-72329.firebaseapp.com',
    storageBucket: 'login-72329.appspot.com',
    measurementId: 'G-V1CEKKX5PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqkTzzW8DTYPnTEyOyGtU7INj8Umg8wJ8',
    appId: '1:212179119317:android:5893f00c2441e905edc65c',
    messagingSenderId: '212179119317',
    projectId: 'login-72329',
    storageBucket: 'login-72329.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtaquZQV86s3FJiWxX93fLvZiPynytCYQ',
    appId: '1:212179119317:ios:45ca82f55e805a7eedc65c',
    messagingSenderId: '212179119317',
    projectId: 'login-72329',
    storageBucket: 'login-72329.appspot.com',
    iosClientId: '212179119317-gnu654q7ucd7tr2cprltd1acqes269k1.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalBarnyardDefenders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtaquZQV86s3FJiWxX93fLvZiPynytCYQ',
    appId: '1:212179119317:ios:4203ebf5d46775d2edc65c',
    messagingSenderId: '212179119317',
    projectId: 'login-72329',
    storageBucket: 'login-72329.appspot.com',
    iosClientId: '212179119317-f0kg3ncsdecfcdtggb298st48v9j7v9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalBarnyardDefenders.RunnerTests',
  );
}
